In [114]:
import pandas as pd

dataset found here: https://www.statsamerica.org/downloads/default.aspx

In [115]:
# Load the data
population = pd.read_csv('./data/population.csv')

In [116]:
# Check the data
population.head()

,IBRC_Geo_ID,Statefips,Countyfips,Description,Year,Population,Count or Estimate,State or County Release
0,0,0,0,U.S.,1970,203302031,Count,State
1,0,0,0,U.S.,1970,203302037,Estimate,County
2,0,0,0,U.S.,1980,226545805,Count,State
3,0,0,0,U.S.,1980,226542250,Estimate,County
4,0,0,0,U.S.,1990,248790925,Count,State

In [117]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89499 entries, 0 to 89498
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   IBRC_Geo_ID              89499 non-null  int64
 1   Statefips                89499 non-null  int64
 2   Countyfips               89499 non-null  int64
 3   Description              89499 non-null  object
 4   Year                     89499 non-null  int64
 5   Population               89499 non-null  int64
 6   Count or Estimate        89499 non-null  object
 7   State or County Release  89499 non-null  object
dtypes: int64(5), object(3)
memory usage: 5.5+ MB

In [118]:
# Check the unique values in the Description column
population['Description'].unique()

array(['U.S.', 'Alabama', 'Autauga County, AL', ..., 'Uinta County, WY',
       'Washakie County, WY', 'Weston County, WY'], dtype=object)

In [119]:
us_states = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
    'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
    'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
    'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
    'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
    'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
]

# Filter the dataset to keep only records with descriptions that are US states
population = population[population['Description'].isin(us_states)]

# Reset index after filtering
population.reset_index(drop=True, inplace=True)

In [120]:
# Check the data
population

,IBRC_Geo_ID,Statefips,Countyfips,Description,Year,Population,Count or Estimate,State or County Release
0,1000,1,0,Alabama,1970,3444354,Count,State
1,1000,1,0,Alabama,1970,3444354,Estimate,County
2,1000,1,0,Alabama,1980,3894025,Estimate,County
3,1000,1,0,Alabama,1980,3893888,Count,State
4,1000,1,0,Alabama,1990,4040389,Count,State
...,...,...,...,...,...,...,...,...
1496,56000,56,0,Wyoming,2016,585243,Estimate,County
1497,56000,56,0,Wyoming,2017,579994,Estimate,County
1498,56000,56,0,Wyoming,2018,579054,Estimate,County
1499,56000,56,0,Wyoming,2019,580116,Estimate,County
1500,56000,56,0,Wyoming,2020,582328,Estimate,County

In [121]:
# remove the records in the State or County Release column that are "State"
population = population[~population['State or County Release'].str.contains('State')]

In [122]:
# Check the data
population['Year'].unique()

array([1970, 1980, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2020])

In [123]:
population

,IBRC_Geo_ID,Statefips,Countyfips,Description,Year,Population,Count or Estimate,State or County Release
1,1000,1,0,Alabama,1970,3444354,Estimate,County
2,1000,1,0,Alabama,1980,3894025,Estimate,County
6,1000,1,0,Alabama,2000,4447100,Count,County
7,1000,1,0,Alabama,2000,4451497,Estimate,County
8,1000,1,0,Alabama,2001,4463343,Estimate,County
...,...,...,...,...,...,...,...,...
1496,56000,56,0,Wyoming,2016,585243,Estimate,County
1497,56000,56,0,Wyoming,2017,579994,Estimate,County
1498,56000,56,0,Wyoming,2018,579054,Estimate,County
1499,56000,56,0,Wyoming,2019,580116,Estimate,County
1500,56000,56,0,Wyoming,2020,582328,Estimate,County

In [124]:
# Drop the "Count" records from the Count or Estimate column
population = population[~population['Count or Estimate'].str.contains('Count')]

In [125]:
# Check the data
population

,IBRC_Geo_ID,Statefips,Countyfips,Description,Year,Population,Count or Estimate,State or County Release
1,1000,1,0,Alabama,1970,3444354,Estimate,County
2,1000,1,0,Alabama,1980,3894025,Estimate,County
7,1000,1,0,Alabama,2000,4451497,Estimate,County
8,1000,1,0,Alabama,2001,4463343,Estimate,County
9,1000,1,0,Alabama,2002,4471462,Estimate,County
...,...,...,...,...,...,...,...,...
1496,56000,56,0,Wyoming,2016,585243,Estimate,County
1497,56000,56,0,Wyoming,2017,579994,Estimate,County
1498,56000,56,0,Wyoming,2018,579054,Estimate,County
1499,56000,56,0,Wyoming,2019,580116,Estimate,County
1500,56000,56,0,Wyoming,2020,582328,Estimate,County

In [126]:
# remove all columns except Description, Year, and Population
population = population[['Description', 'Year', 'Population']]

In [130]:
# remove columns with duplicate descriptions and years
population = population.drop_duplicates(subset=['Description', 'Year'])

In [131]:
# Check the data
population

     Description  Year  Population
1        Alabama  1970     3444354
2        Alabama  1980     3894025
7        Alabama  2000     4451497
8        Alabama  2001     4463343
9        Alabama  2002     4471462
...          ...   ...         ...
1496     Wyoming  2016      585243
1497     Wyoming  2017      579994
1498     Wyoming  2018      579054
1499     Wyoming  2019      580116
1500     Wyoming  2020      582328

[1150 rows x 3 columns]

In [132]:
# make the years the columns and the states the rows
population = population.pivot(index='Description', columns='Year', values='Population')

In [133]:
# Check the data
population

Year,1970,1980,2000,2001,2002,2003,2004,2005,2006,2007,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Description,,,,,,,,,,,,,,,,,,,,,
Alabama,3444354,3894025,4451497,4463343,4471462,4489876,4510588,4542912,4594911,4634063,...,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4921532
Alaska,302583,401851,627748,633538,641974,647671,659305,667114,675322,679893,...,722349,730810,737626,737075,738430,742575,740983,736624,733603,731158
Arizona,1775399,2716546,5166304,5303869,5451472,5590820,5758692,5973970,6190987,6360238,...,6473416,6556344,6634690,6732873,6832810,6944767,7048088,7164228,7291843,7421401
Arkansas,1923322,2286358,2678115,2690743,2704471,2722804,2746215,2776257,2814910,2841595,...,2941038,2952876,2960459,2968759,2979732,2991815,3003855,3012161,3020985,3030522
California,19971071,23667764,33994383,34481753,34867773,35236589,35538256,35770688,35947461,36185908,...,37636311,37944551,38253768,38586706,38904296,39149186,39337785,39437463,39437610,39368078
Colorado,2209596,2889735,4328277,4432779,4502883,4545766,4595674,4655731,4747872,4837229,...,5121900,5193660,5270774,5352637,5454328,5543844,5617421,5697155,5758486,5807719
Connecticut,3032217,3107564,3411506,3428043,3448145,3468319,3474379,3477185,3484531,3488084,...,3588632,3595211,3595792,3595697,3588561,3579830,3575324,3574561,3566022,3557006
Delaware,548104,594338,786417,794954,804636,815525,827154,840296,853301,865314,...,907590,915518,924062,933131,942065,949989,957942,966985,976668,986809
Florida,6791418,9746959,16046148,16350988,16675166,16974177,17366358,17773291,18076361,18262096,...,19055607,19302016,19551678,19853880,20219111,20627237,20977089,21254926,21492056,21733312
Georgia,4587930,5462989,8230306,8418687,8582756,8727810,8907292,9090479,9323575,9526642,...,9803630,9903580,9975592,10071204,10183353,10308442,10417031,10519389,10628020,10710017
Hawaii,769913,964691,1212396,1218790,1226410,1231632,1246872,1259147,1269228,1269796,...,1379562,1395199,1408822,1415335,1422999,1428885,1425763,1423102,1415615,1407006
Idaho,713015,944127,1299555,1320791,1341704,1363672,1391127,1425226,1463631,1498390,...,1584272,1595910,1612053,1632248,1652495,1684036,1719745,1752074,1789060,1826913
Illinois,11110288,11427429,12437568,12506636,12557032,12599246,12644218,12672835,12714588,12775864,...,12867783,12883029,12895778,12885092,12859585,12821709,12779893,12724685,12667017,12587530
Indiana,5195392,5490210,6091517,6124090,6148648,6184552,6214844,6253142,6300341,6344771,...,6517250,6538989,6570575,6596019,6611442,6637898,6662068,6698481,6731010,6754953
Iowa,2825368,2913808,2928191,2929240,2929379,2934585,2942311,2950517,2965203,2979867,...,3066772,3076844,3093935,3110643,3122541,3133210,3143734,3149900,3159596,3163561
Kansas,2249071,2364236,2692907,2701167,2711741,2720361,2729378,2739997,2754018,2773740,...,2869677,2886024,2894306,2901861,2910717,2912977,2910892,2912748,2912635,2913805
Kentucky,3220711,3660334,4048714,4068775,4090824,4117691,4145777,4179655,4216783,4254513,...,4370817,4387865,4406906,4416992,4429126,4440306,4455590,4464273,4472345,4477251
Louisiana,3644637,4206124,4468970,4460400,4465089,4473198,4487246,4495113,4237693,4373448,...,4576244,4602067,4626040,4645938,4666998,4681346,4673673,4664450,4658285,4645318
Maine,993722,1125043,1277040,1284295,1293181,1302365,1307227,1310424,1313479,1315749,...,1328473,1328094,1328543,1331217,1329098,1332348,1335743,1340123,1345770,1350141
Maryland,3923897,4216933,5310504,5374009,5437880,5491971,5537913,5576889,5605552,5627211,...,5840241,5888375,5925197,5960064,5988528,6007014,6028186,6042153,6054954,6055802
Massachusetts,5689170,5737093,6362498,6411336,6440762,6455028,6452636,6453694,6466069,6499672,...,6614218,6664269,6715158,6764864,6797484,6827280,6863560,6885720,6894883,6893574
Michigan,8881826,9262044,9954984,10005334,10039223,10072219,10091511,10092426,10082414,10051145,...,9883053,9898289,9914802,9932033,9934483,9954117,9976752,9987286,9984795,9966555
Minnesota,3806103,4075970,4933739,4982180,5017355,5050393,5080031,5106992,5147857,5191267,...,5346620,5377500,5414722,5452665,5484002,5525360,5569283,5608762,5640053,5657342
Mississippi,2216994,2520770,2848433,2853090,2858076,2866386,2884920,2899300,2896691,2920312,...,2979147,2984599,2989839,2991892,2990231,2990595,2990674,2982879,2978227,2966786
Missouri,4677623,4916766,5605714,5642852,5679158,5713051,5755931,5803587,5857974,5905750,...,6011182,6026027,6042989,6059130,6075411,6091384,6111382,6125986,6140475,6151548
Montana,694409,786690,903305,905782,909722,916620,925711,934656,946059,957123,...,997518,1004168,1014158,1022657,1031495,1042137,1053862,1061818,1070123,1080577
Nebraska,1485333,1569825,1713279,1717672,1724577,1733099,1741417,1750772,1759327,1768745,...,1840914,1853691,1865813,1879955,1892059,1906483,1916998,1925512,1932571,1937552
Nevada,488738,800508,2018196,2094338,2165828,2236378,2327547,2407073,2491122,2564816,...,2713114,2744670,2776956,2818935,2868531,2919555,2972097,3030725,3090771,3138259
New Hampshire,737681,920610,1240385,1256685,1270962,1282146,1292566,1301050,1311184,1316496,...,1320444,1324677,1327272,1334257,1337480,1343694,1350395,1355064,1360783,1366275
New Jersey,7171112,7365011,8430799,8488427,8543281,8585567,8610474,8619564,8619354,8630810,...,8828552,8845671,8857821,8867277,8870312,8873584,8888147,8891730,8891258,8882371
New Mexico,1017055,1303303,1820802,1828437,1849187,1868121,1890215,1914699,1940631,1966357,...,2080707,2087715,2092833,2090236,2090071,2092555,2092844,2093754,2099634,2106319
New York,18241391,17558165,18996959,19087486,19161568,19235015,19297907,19329398,19353588,19419540,...,19499921,19574362,19626488,19653431,19657321,19636391,19593849,19544098,19463131,19336776
North Carolina,5084411,5880096,8080253,8202468,8311105,8399815,8517909,8655414,8853849,9047856,...,9658913,9751810,9846717,9937295,10037218,10161802,10275758,10391358,10501384,10600823
North Dakota,617792,652717,641298,636225,633210,631680,635480,634528,636019,637534,...,685526,702227,723149,738736,755537,756114,756755,760062,763724,765309
Ohio,10657423,10797604,11363136,11395572,11420660,11450398,11465854,11475559,11490596,11518989,...,11545735,11550971,11579692,11606573,11622315,11640060,11665706,11680892,11696507,11693217
Oklahoma,2559463,3025487,3453891,3463996,3483149,3495502,3511467,3530037,3571612,3608759,...,3788824,3819320,3853891,3879187,3910518,3928143,3933602,3943488,3960676,3980783
Oregon,2091533,2633156,3430739,3469878,3516661,3551290,3573214,3617086,3675743,3730833,...,3872672,3900102,3924110,3965447,4018542,4093271,4147294,4183538,4216116,4241507
Pennsylvania,11800766,11864720,12283881,12296977,12324237,12360988,12387357,12415908,12466485,12517701,...,12747052,12769123,12779538,12792392,12789838,12788468,12794679,12809107,12798883,12783254
Rhode Island,949722,947154,1050607,1057707,1066919,1072453,1075835,1069226,1064193,1059706,...,1053829,1054893,1055560,1056511,1056886,1057816,1056554,1059338,1058158,1057125
South Carolina,2590713,3120737,4024082,4062301,4102227,4141080,4196549,4250989,4334146,4417059,...,4672655,4719027,4766469,4826858,4896006,4963031,5027102,5091702,5157702,5218040
South Dakota,666257,690768,755707,758803,761633,765980,773087,778775,786973,795521,...,823740,833859,842751,849670,854663,863693,873732,879386,887127,892717
Tennessee,3926018,4591023,5703129,5754748,5802304,5856712,5918897,5997481,6090290,6172788,...,6400298,6455752,6496943,6544617,6595354,6651277,6714748,6778180,6830325,6886834
Texas,11198657,14225512,20944937,21330190,21705766,22048452,22408514,22790696,23356591,23824518,...,25645504,26084120,26479646,26963092,27468531,27914064,28291024,28624564,28986794,29360759
Utah,1059273,1461037,2244207,2290966,2334425,2378255,2438195,2498863,2582234,2662908,...,2814797,2854146,2898773,2938327,2983626,3044241,3103540,3155153,3203383,3249879
Vermont,444732,511456,609658,611889,614753,616700,618120,618797,619916,620438,...,627197,626361,626603,625693,625810,624366,625132,624802,624046,623347
Virginia,4651448,5346797,7105425,7191579,7277452,7352164,7453994,7547753,7633859,7705466,...,8102437,8187456,8255861,8315430,8367303,8417651,8471011,8510920,8556642,8590563
Washington,3413244,4132353,5911439,5988346,6056348,6108738,6181646,6258988,6371097,6464167,...,6827479,6898599,6966252,7057531,7167287,7299961,7427951,7526793,7614024,7693612
West Virginia,1744237,1950183,1806694,1798190,1799219,1802916,1803462,1804128,1808136,1812295,...,1856606,1857446,1854768,1850569,1843332,1832435,1818683,1805953,1795263,1784787
Wisconsin,4417821,4705642,5373849,5408099,5446571,5479542,5512205,5542096,5571510,5601508,...,5705840,5720825,5738012,5753199,5762927,5775170,5793147,5809319,5824581,5832655
Wyoming,332416,469557,493980,492976,496930,498865,502742,506002,512664,523226,...,567491,576656,582620,583159,586389,585243,579994,579054,580116,582328

In [135]:
# Save the cleaned data
population.to_csv('./data/population_cleaned.csv')